import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import loginData from "../Test-data/login.json";
import ipecMHFee from "../Test-data/manualHanldingIPEC.json";

for(const ipec of ipecMHFee){
test.setTimeout(60000)
test(`The testcase ID ${ipec.testTitle}`,async ({page,context}) => {
    const login = new LoginPage(page,context)
    await login.loadingURL()
    await login.enteringUsername(loginData.username)
    await login.enteringPassword(loginData.password)
    await login.clickingContinueButton()
    await login.loginPageSpinner()
    await page.waitForTimeout(3000)
    const exportDomestic = new ExportDomesticPage(page,context)
    await exportDomestic.enteringDeliveryCompanyName(ipec.delCompany)
    await exportDomestic.enteringDeliveryContactName(ipec.delContact)
    await exportDomestic.enteringDeliveryAddress1(ipec.delAddress1)
    await exportDomestic.clickingDeliveryCountry(ipec.delCountry)
    await exportDomestic.clickingDeliveryState(ipec.delState)
    await exportDomestic.enteringDeliveryCity(ipec.delCity)
    await exportDomestic.enteringDeliveryPostcode(ipec.delPostcode)
    await exportDomestic.enteringDeliveryDial(ipec.delDial)
    await exportDomestic.enteringDeliveryPhone(ipec.delPhone)
    await exportDomestic.enteringDeliveryEmailID(ipec.delEmail)
    await exportDomestic.clickingServiceCompany(ipec.carrier)
    await exportDomestic.clickingServiceType(ipec.serviceType)
    await exportDomestic.clickingPackageType(ipec.packageType)
    await exportDomestic.enteringCustomerRef(ipec.customerReference)
    await exportDomestic.enteringTestDescription(ipec.testDescription)
    await exportDomestic.clickingTransitInsurance(ipec.transitInsurance)
    await exportDomestic.enteringWeight(ipec.weight)
    await exportDomestic.enteringLength(ipec.length)
    await exportDomestic.enteringWidth(ipec.width)
    await exportDomestic.enteringHeight(ipec.height)
    await exportDomestic.chooseMultipleItems(ipec.count)
    await exportDomestic.clickingCopytoAllIcon()
    await exportDomestic.clickingQuoteButton()
    await exportDomestic.exportPageSpinner()
    await exportDomestic.gettingMHFee()
    //await exportDomestic.clickingOKButton()
    /*await exportDomestic.clickingNextButton()
    await exportDomestic.exportPageSpinner()
    const collectionOption = new CollectionOptionPage(page,context)
    await collectionOption.clickingDropAtDepot()
    //await collectionOption.clickingScheduleACollection(exportPage.date,exportPage.parcelFrom,exportPage.closePickup,exportPage.pickupLoc,exportPage.locationDesc)
    await collectionOption.clickingShipButton()
    await collectionOption.collectionPageSpinner()
    await page.waitForTimeout(3000)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    await lablesAndShippingDocs.gettingSuccessMessage()
    await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewReceipt()
    await page.waitForTimeout(4000)*/
})}