import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import loginData from "../Test-data/login.json";
import oversizeIPECCharges from "../Test-data/oversizeIPEC.json";

for(const oversizeIpec of oversizeIPECCharges){
test.setTimeout(60000)
test(`The testcase ID ${oversizeIpec.testTitle}`,async ({page,context}) => {
    const login = new LoginPage(page,context)
    await login.loadingURL()
    await login.enteringUsername(loginData.username)
    await login.enteringPassword(loginData.password)
    await login.clickingContinueButton()
    await login.loginPageSpinner()
    await page.waitForTimeout(3000)
    const exportDomestic = new ExportDomesticPage(page,context)
    await exportDomestic.enteringDeliveryCompanyName(oversizeIpec.delCompany)
    await exportDomestic.enteringDeliveryContactName(oversizeIpec.delContact)
    await exportDomestic.enteringDeliveryAddress1(oversizeIpec.delAddress1)
    await exportDomestic.clickingDeliveryCountry(oversizeIpec.delCountry)
    await exportDomestic.clickingDeliveryState(oversizeIpec.delState)
    await exportDomestic.enteringDeliveryCity(oversizeIpec.delCity)
    await exportDomestic.enteringDeliveryPostcode(oversizeIpec.delPostcode)
    await exportDomestic.enteringDeliveryDial(oversizeIpec.delDial)
    await exportDomestic.enteringDeliveryPhone(oversizeIpec.delPhone)
    await exportDomestic.enteringDeliveryEmailID(oversizeIpec.delEmail)
    await exportDomestic.clickingServiceCompany(oversizeIpec.carrier)
    await exportDomestic.clickingServiceType(oversizeIpec.serviceType)
    await exportDomestic.clickingPackageType(oversizeIpec.packageType)
    await exportDomestic.enteringCustomerRef(oversizeIpec.customerReference)
    await exportDomestic.enteringTestDescription(oversizeIpec.testDescription)
    await exportDomestic.clickingTransitInsurance(oversizeIpec.transitInsurance)
    await exportDomestic.enteringWeight(oversizeIpec.weight)
    await exportDomestic.enteringLength(oversizeIpec.length)
    await exportDomestic.enteringWidth(oversizeIpec.width)
    await exportDomestic.enteringHeight(oversizeIpec.height)
    await exportDomestic.chooseMultipleItems(oversizeIpec.count)
    await exportDomestic.clickingCopytoAllIcon()
    await exportDomestic.clickingQuoteButton()
    await exportDomestic.exportPageSpinner()
    await exportDomestic.gettingMHFee()
    /*await exportDomestic.clickingOKButton()
    await exportDomestic.clickingNextButton()
    await exportDomestic.exportPageSpinner()
    const collectionOption = new CollectionOptionPage(page,context)
    await collectionOption.clickingDropAtDepot()
    //await collectionOption.clickingScheduleACollection(exportPage.date,exportPage.parcelFrom,exportPage.closePickup,exportPage.pickupLoc,exportPage.locationDesc)
    await collectionOption.clickingShipButton()
    await collectionOption.collectionPageSpinner()
    await page.waitForTimeout(3000)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    await lablesAndShippingDocs.gettingSuccessMessage()
    await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewReceipt()
    await page.waitForTimeout(4000)*/
})}