import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import loginData from "../Test-data/login.json";
import oversizePriorityCharges from "../Test-data/oversizePriority.json";

for(const oversizePriority of oversizePriorityCharges){
test.setTimeout(60000)
test(`The testcase ID ${oversizePriority.testTitle}`,async ({page,context}) => {
    const login = new LoginPage(page,context)
    await login.loadingURL()
    await login.enteringUsername(loginData.username)
    await login.enteringPassword(loginData.password)
    await login.clickingContinueButton()
    await login.loginPageSpinner()
    await page.waitForTimeout(3000)
    const exportDomestic = new ExportDomesticPage(page,context)
    await exportDomestic.enteringDeliveryCompanyName(oversizePriority.delCompany)
    await exportDomestic.enteringDeliveryContactName(oversizePriority.delContact)
    await exportDomestic.enteringDeliveryAddress1(oversizePriority.delAddress1)
    await exportDomestic.clickingDeliveryCountry(oversizePriority.delCountry)
    await exportDomestic.clickingDeliveryState(oversizePriority.delState)
    await exportDomestic.enteringDeliveryCity(oversizePriority.delCity)
    await exportDomestic.enteringDeliveryPostcode(oversizePriority.delPostcode)
    await exportDomestic.enteringDeliveryDial(oversizePriority.delDial)
    await exportDomestic.enteringDeliveryPhone(oversizePriority.delPhone)
    await exportDomestic.enteringDeliveryEmailID(oversizePriority.delEmail)
    await exportDomestic.clickingServiceCompany(oversizePriority.carrier)
    await exportDomestic.clickingServiceType(oversizePriority.serviceType)
    await exportDomestic.clickingPackageType(oversizePriority.packageType)
    await exportDomestic.enteringCustomerRef(oversizePriority.customerReference)
    await exportDomestic.enteringTestDescription(oversizePriority.testDescription)
    await exportDomestic.clickingTransitInsurance(oversizePriority.transitInsurance)
    await exportDomestic.enteringWeight(oversizePriority.weight)
    await exportDomestic.enteringLength(oversizePriority.length)
    await exportDomestic.enteringWidth(oversizePriority.width)
    await exportDomestic.enteringHeight(oversizePriority.height)
    await exportDomestic.chooseMultipleItems(oversizePriority.count)
    await exportDomestic.clickingCopytoAllIcon()
    await exportDomestic.clickingQuoteButton()
    await exportDomestic.exportPageSpinner()
    await exportDomestic.gettingMHFee()
    /*await exportDomestic.clickingOKButton()
    await exportDomestic.clickingNextButton()
    await exportDomestic.exportPageSpinner()
    const collectionOption = new CollectionOptionPage(page,context)
    await collectionOption.clickingDropAtDepot()
    //await collectionOption.clickingScheduleACollection(exportPage.date,exportPage.parcelFrom,exportPage.closePickup,exportPage.pickupLoc,exportPage.locationDesc)
    await collectionOption.clickingShipButton()
    await collectionOption.collectionPageSpinner()
    await page.waitForTimeout(3000)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    await lablesAndShippingDocs.gettingSuccessMessage()
    await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewReceipt()
    await page.waitForTimeout(4000)*/
})}