import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import loginData from "../Test-data/login.json";
import  priorityMHFee  from "../Test-data/manualHandlingPriority.json";

for(const priority of priorityMHFee){
test.setTimeout(60000)
test(`The testcase ID ${priority.testTitle}`,async ({page,context}) => {
    const login = new LoginPage(page,context)
    await login.loadingURL()
    await login.enteringUsername(loginData.username)
    await login.enteringPassword(loginData.password)
    await login.clickingContinueButton()
    await login.loginPageSpinner()
    await page.waitForTimeout(3000)
    const exportDomestic = new ExportDomesticPage(page,context)
    await exportDomestic.enteringDeliveryCompanyName(priority.delCompany)
    await exportDomestic.enteringDeliveryContactName(priority.delContact)
    await exportDomestic.enteringDeliveryAddress1(priority.delAddress1)
    await exportDomestic.clickingDeliveryCountry(priority.delCountry)
    await exportDomestic.clickingDeliveryState(priority.delState)
    await exportDomestic.enteringDeliveryCity(priority.delCity)
    await exportDomestic.enteringDeliveryPostcode(priority.delPostcode)
    await exportDomestic.enteringDeliveryDial(priority.delDial)
    await exportDomestic.enteringDeliveryPhone(priority.delPhone)
    await exportDomestic.enteringDeliveryEmailID(priority.delEmail)
    await exportDomestic.clickingServiceCompany(priority.carrier)
    await exportDomestic.clickingServiceType(priority.serviceType)
    await exportDomestic.clickingPackageType(priority.packageType)
    await exportDomestic.enteringCustomerRef(priority.customerReference)
    await exportDomestic.enteringTestDescription(priority.testDescription)
    await exportDomestic.clickingTransitInsurance(priority.transitInsurance)
    await exportDomestic.enteringWeight(priority.weight)
    await exportDomestic.enteringLength(priority.length)
    await exportDomestic.enteringWidth(priority.width)
    await exportDomestic.enteringHeight(priority.height)
    await exportDomestic.chooseMultipleItems(priority.count)
    await exportDomestic.clickingCopytoAllIcon()
    await exportDomestic.clickingQuoteButton()
    await exportDomestic.exportPageSpinner()
    await exportDomestic.gettingMHFee()
    /*await exportDomestic.clickingOKButton()
    await exportDomestic.clickingNextButton()
    await exportDomestic.exportPageSpinner()
    const collectionOption = new CollectionOptionPage(page,context)
    await collectionOption.clickingDropAtDepot()
    //await collectionOption.clickingScheduleACollection(exportPage.date,exportPage.parcelFrom,exportPage.closePickup,exportPage.pickupLoc,exportPage.locationDesc)
    await collectionOption.clickingShipButton()
    await collectionOption.collectionPageSpinner()
    await page.waitForTimeout(3000)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    await lablesAndShippingDocs.gettingSuccessMessage()
    await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewReceipt()
    await page.waitForTimeout(4000)*/
})}