import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { QuickQuotePage } from "../Pages/QuickQuotePage";
import { QuickQuoteRatesPage } from "../Pages/QuickQuoteRatesPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import { CollectionOptionPage } from "../Pages/CollectionOptionPage";
import { LabelsAndDocumentsPage } from "../Pages/LabelsAndDocumentsPage";
import { TrackingHistoryPage } from "../Pages/TrackingHistoryPage";
import { CommercialInvoicePage } from "../Pages/CommercialInvoicePage";
import quickQuoteTest from "../Test-data/quickQuoteInternational.json";

for(const quickQuoteTestData of quickQuoteTest){
test.setTimeout(1200000)
test(`The test title ${quickQuoteTestData.testTitle}`, async ({page,context}) => {
    const login = new LoginPage(page,context)
    const quickQuote = new QuickQuotePage(page,context)
    const quickQuoteRate = new QuickQuoteRatesPage(page,context)
    const exportPage = new ExportDomesticPage(page,context)
    const collectionPage = new CollectionOptionPage(page,context)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    const trackingHistory = new TrackingHistoryPage(page,context)
    const commercialInvoice = new CommercialInvoicePage(page,context)

    await login.loadingURL()
    await quickQuote.clickingQuickQuotePage()
    await quickQuote.quickQuoteSpinner()
    await quickQuote.clickingParcelorPallet(quickQuoteTestData.serviceType)
    await quickQuote.clickingFromCountry(quickQuoteTestData.fromCountry)  //Choosing collection country
    await quickQuote.clickingToCountry(quickQuoteTestData.toCountry)      //Choosing delivery country
    await quickQuote.enteringFromPostcode(quickQuoteTestData.fromPostcode)
    await quickQuote.enteringFromState(quickQuoteTestData.fromState)
    await quickQuote.enteringFromCity(quickQuoteTestData.fromCity)
    await quickQuote.enteringDeliveryPostcode(quickQuoteTestData.toPostcode)
    await quickQuote.enteringDeliveryState(quickQuoteTestData.toState)
    await quickQuote.enteringDeliveryCity(quickQuoteTestData.toCity)
    await quickQuote.enteringWeight(quickQuoteTestData.weight)
    await quickQuote.enteringLength(quickQuoteTestData.length)
    await quickQuote.enteringWidth(quickQuoteTestData.width)
    await quickQuote.enteringHeight(quickQuoteTestData.height)
    await quickQuote.clickingMultiplePieces(quickQuoteTestData.count)
    await quickQuote.clickingResidentialCollection(quickQuoteTestData.residentialCollection)
    await quickQuote.clickingResidentialDelivery(quickQuoteTestData.residentialDelivery)
    await quickQuote.clickingPickupTailLift(quickQuoteTestData.tailLiftCollection)
    await quickQuote.clickingDeliveryTailLift(quickQuoteTestData.tailLiftDelivery)
    await quickQuote.clickingDangerousGoods(quickQuoteTestData.DangerousGoods)
    await quickQuote.clickingFedExDSR(quickQuoteTestData.FedExDSR)
    await quickQuote.clickingFedEXASR(quickQuoteTestData.FedExASR)
    await quickQuote.clickingFedExISR(quickQuoteTestData.FedExISR)
    await quickQuote.clickingQuoteButton()
    await quickQuote.quickQuoteSpinner()
    await quickQuoteRate.quickQuoteCarrierSpinner()
    await quickQuoteRate.choosingInternationalCarriers(quickQuoteTestData.serviceType,quickQuoteTestData.serviceName)  //Choosing carrier
    await quickQuoteRate.quickQuoteRatePageSpinner()
    await page.waitForTimeout(3000)
    await exportPage.enteringCollectionCompanyName(quickQuoteTestData.collectionCompany)
    await exportPage.enteringCollectionContactName(quickQuoteTestData.collectionConctact)
    await exportPage.enteringCollectionAddress1(quickQuoteTestData.collectionAddress1)
    await exportPage.enteringCollectionDial(quickQuoteTestData.collectionDial)
    await exportPage.enteringCollectionPhone(quickQuoteTestData.collectionPhone)
    await exportPage.enteringCollectionEmailID(quickQuoteTestData.collectionEmail)
    await exportPage.enteringDeliveryCompanyName(quickQuoteTestData.deliveryCompany)
    await exportPage.enteringDeliveryContactName(quickQuoteTestData.deliveryContact)
    await exportPage.enteringDeliveryAddress1(quickQuoteTestData.deliveryAddress1)
    await exportPage.enteringDeliveryDial(quickQuoteTestData.deliveryDial)
    await exportPage.enteringDeliveryPhone(quickQuoteTestData.deliveryPhone)
    await exportPage.enteringDeliveryEmailID(quickQuoteTestData.deliveryEmail)
    await exportPage.enteringCustomerRef(quickQuoteTestData.customerRef)
    await exportPage.enteringTestDescription(quickQuoteTestData.description)
    await exportPage.clickingTransitInsurance(quickQuoteTestData.insurance)
    await exportPage.choosingCurrencyType(quickQuoteTestData.currency)
    await exportPage.enteringCustomValue(quickQuoteTestData.customValue)
    await exportPage.clickingQuoteButton()
    await exportPage.exportPageSpinner()
    await exportPage.gettingRatesOrErrorMessage()
    await exportPage.clickingOKButton()
    await exportPage.clickingNextButton()
    await exportPage.exportPageSpinner()
    await commercialInvoice.readingQuoteAndPriceDetails()
    await commercialInvoice.choosingCommercialInvoice(quickQuoteTestData.invoiceType,quickQuoteTestData.paperOrDigital,quickQuoteTestData.eORI,quickQuoteTestData.tAXID,quickQuoteTestData.iTNNumber,quickQuoteTestData.invoiceNo,quickQuoteTestData.goodsDescription,quickQuoteTestData.invoiceWeight,quickQuoteTestData.sourceCountry,quickQuoteTestData.commodityCode,quickQuoteTestData.quantity,quickQuoteTestData.unitPrice)
    await collectionPage.readingQuoteAndPriceDetails()
    await collectionPage.clickingDropAtDepot()
    await collectionPage.clickingShipButton()
    await collectionPage.collectionPageSpinner()
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.gettingSuccessMessage()
    const trackingNumber = await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel([quickQuoteTestData.labelUrl,trackingNumber])
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.clickingViewReceipt(quickQuoteTestData.receiptUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintCommercialInvoice(quickQuoteTestData.commercialInvoiceUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintManifest(quickQuoteTestData.manifestUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingTrackingHistory()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await trackingHistory.filteringConsingment(quickQuoteTestData.filterBy,trackingNumber)
    await trackingHistory.clickingRow(trackingNumber)
    await trackingHistory.trackingHistoryPageSpinner()
    await trackingHistory.clickingTrackingAndPOD()
    await trackingHistory.clickShippingDocument([quickQuoteTestData.labelUrl,trackingNumber],quickQuoteTestData.receiptUrl,quickQuoteTestData.manifestUrl,quickQuoteTestData.mailTo,quickQuoteTestData.starTrackManifest,quickQuoteTestData.filterBy,quickQuoteTestData.commercialInvoiceUrl,quickQuoteTestData.commercialInvoiceLogoUrl)
    await page.waitForTimeout(4000)
    await trackingHistory.clickingVoidButton()
    await page.waitForTimeout(3000)
    
})}